### ISSUE TITLE
Engines not working

### ISSUE THREAD

**Issue by Athrekas** [Patrowl/PatrowlDocs#10]
If I use the docker-start-engines script, it creates all the dockers but not show up on the Engines interface.
If I create a docker manually, the same thing happens. Adding a scan engine via web seems to not work.

![image](https://user-images.githubusercontent.com/23584901/47364205-00889b00-d6d9-11e8-9d34-31f8223967ac.png)

![image](https://user-images.githubusercontent.com/23584901/47364240-18601f00-d6d9-11e8-806a-7bb7eaf35560.png)

**Comment by Athrekas** [comment]
Going to try and install without dockers to see if the error is docker related.

**Comment by MaKyOtOx** [comment]
any updates ?

**Comment by joaodomingos** [comment]
Having the same problem with dockers, I run nmap engine in a docker instance with the IP 172.17.0.2 so when I configure the new engine, the URL should be "http://172.17.0.2:5001/engines/nmap/" right?

**Comment by MaKyOtOx** [comment]
Yes, the URL is right (if the engine actually expose the TCP port 5001 on ip iface 172.17.0.2 ;)).

Try to start the docker engine using this command (using the docker image hosted on Docker Hub):
`docker run -d --rm -p 5001:5001 --name="nmap-docker-001" -v nmap.json.sample:/opt/patrowl-engines/nmap/nmap.json:ro patrowl/engine-nmap`

**Comment by emilva** [comment]
Hi, same problem where.
When running `docker run -d --rm -p 5001:5001 --name="nmap-docker-001" -v nmap.json.sample:/opt/patrowl-engines/nmap/nmap.json:ro patrowl/engine-nmap` 
I get `docker: Error response from daemon: source is not directory.`

FYI I am standing in the `PatrowlEngines/engines/nmap` directory, so the file nmap.json file is available.

**Comment by MaKyOtOx** [comment]
Hi, I've reproduced the bug. There is an issue with the path used to mont the file/volume in the docker container.
Try this command: `docker run -d --rm -p 5001:5001 --name="nmap-docker-001" -v $(pwd)/nmap.json.sample:/opt/patrowl-engines/nmap/nmap.json:ro patrowl/engine-nmap`

**Comment by emilva** [comment]
Thanks, that fixed it!

**Comment by exenin** [comment]
I had a problem where the docker engine container could not communicate with django container.
This was due to them being on different docker networks.
docker inspect patrowl-django
  ```
          "Networks": {                                                                                                               │n-censys,monitor-censys --purge --without-mingle --without-gossip -Ofair
                "**patrowlmanager_default**": {

```
so when running my engines i just add the --network=patrowlmanager_default   flag to each.
Then patrowl-django management can add engines using the docker engines container name when adding to engines in management
