### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by dsever** [Patrowl/PatrowlDocs#11]
Hi, 
I like this project, but something is missing :)
Is there any plan to speed up of API documentation? Maybe swagger would be good idea to to start?
There is lot's of plans in roadmap, and I believe that community would like to contribute.

Dubravko

**Comment by dsever** [comment]
I've checked swagger integration within your code, it is straight forward. (I believe you already know that)

Inside of app.urls  is missing:
from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title='Pastebin API')

url(r'^apibrowser$', schema_view),

**Comment by MaKyOtOx** [comment]
done :)
See [Engines](https://github.com/Patrowl/PatrowlDocs/blob/master/api/api-patrowl-engines.md) and [Manager](https://github.com/Patrowl/PatrowlDocs/blob/master/api/api-patrowl-manager.md)
