### ISSUE TITLE
GET /static/css/bootstrap.min.css HTTP/1.1" 404

### ISSUE THREAD

**Issue by ghost** [Patrowl/PatrowlDocs#12]
Hi guys,

After installing everything, I'm getting the above errors when accessing via browser:

27.0.0.1 - - [06/Dec/2018:00:28:45 +0100] "GET /static/css/cal-heatmap.css HTTP/1.1" 404 100 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:45 +0100] "GET /static/css/jquery-ui.css HTTP/1.1" 404 98 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:45 +0100] "GET /static/js/jquery.min.js HTTP/1.1" 404 97 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:45 +0100] "GET /static/js/jquery-ui.min.js HTTP/1.1" 404 100 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:45 +0100] "GET /static/js/bootstrap.min.js HTTP/1.1" 404 100 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:46 +0100] "GET /static/css/jquery.dataTables.min.css HTTP/1.1" 404 110 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:46 +0100] "GET /static/css/datetimepicker.css HTTP/1.1" 404 103 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:46 +0100] "GET /static/css/bootstrap-tagsinput.css HTTP/1.1" 404 108 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:46 +0100] "GET /static/css/bootstrap.min.css HTTP/1.1" 404 102 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:46 +0100] "GET /static/js/tether.min.js HTTP/1.1" 404 97 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:46 +0100] "GET /static/js/d3.min.js HTTP/1.1" 404 93 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:46 +0100] "GET /static/js/cal-heatmap.min.js HTTP/1.1" 404 102 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:46 +0100] "GET /static/js/Chart.bundle.min.js HTTP/1.1" 404 103 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:47 +0100] "GET /static/js/jquery.dataTables.min.js HTTP/1.1" 404 108 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:47 +0100] "GET /static/js/bootstrap-datetimepicker.js HTTP/1.1" 404 111 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:47 +0100] "GET /static/js/typeahead/typeahead.bundle.min.js HTTP/1.1" 404 117 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:47 +0100] "GET /static/js/fontawesome-all.min.js HTTP/1.1" 404 106 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:47 +0100] "GET /static/js/bootstrap-tagsinput.min.js HTTP/1.1" 404 110 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:47 +0100] "GET /admin/jsi18n/ HTTP/1.1" 302 0 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:47 +0100] "GET /static/admin/js/core.js HTTP/1.1" 404 97 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:47 +0100] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 404 113 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:48 +0100] "GET /static/admin/js/jquery.init.js HTTP/1.1" 404 104 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:48 +0100] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 404 119 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:48 +0100] "GET /static/admin/js/actions.js HTTP/1.1" 404 100 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:48 +0100] "GET /static/admin/js/urlify.js HTTP/1.1" 404 99 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:48 +0100] "GET /static/admin/js/prepopulate.js HTTP/1.1" 404 104 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:48 +0100] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 404 115 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:49 +0100] "GET /static/admin/js/calendar.js HTTP/1.1" 404 101 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:49 +0100] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 404 116 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:49 +0100] "GET /static/js/jquery-ui.min.js HTTP/1.1" 404 100 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:49 +0100] "GET /login?next=/admin/jsi18n/ HTTP/1.1" 200 9124 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:49 +0100] "GET /static/js/bootstrap.min.js HTTP/1.1" 404 100 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:49 +0100] "GET /static/js/tether.min.js HTTP/1.1" 404 97 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:49 +0100] "GET /static/js/d3.min.js HTTP/1.1" 404 93 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:50 +0100] "GET /static/js/cal-heatmap.min.js HTTP/1.1" 404 102 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:50 +0100] "GET /static/js/Chart.bundle.min.js HTTP/1.1" 404 103 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:50 +0100] "GET /static/js/jquery.dataTables.min.js HTTP/1.1" 404 108 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:50 +0100] "GET /static/css/jquery.dataTables.min.css HTTP/1.1" 404 110 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:50 +0100] "GET /static/css/datetimepicker.css HTTP/1.1" 404 103 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:50 +0100] "GET /static/js/bootstrap-datetimepicker.js HTTP/1.1" 404 111 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:50 +0100] "GET /static/js/typeahead/typeahead.bundle.min.js HTTP/1.1" 404 117 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:51 +0100] "GET /static/js/fontawesome-all.min.js HTTP/1.1" 404 106 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:51 +0100] "GET /static/js/bootstrap-tagsinput.min.js HTTP/1.1" 404 110 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:51 +0100] "GET /static/css/bootstrap-tagsinput.css HTTP/1.1" 404 108 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:51 +0100] "GET /static/admin/js/core.js HTTP/1.1" 404 97 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:51 +0100] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 404 113 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:51 +0100] "GET /static/admin/js/jquery.init.js HTTP/1.1" 404 104 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:51 +0100] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 404 119 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:51 +0100] "GET /static/admin/js/actions.js HTTP/1.1" 404 100 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:52 +0100] "GET /static/admin/js/urlify.js HTTP/1.1" 404 99 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:52 +0100] "GET /static/admin/js/prepopulate.js HTTP/1.1" 404 104 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:52 +0100] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 404 115 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:52 +0100] "GET /static/admin/js/calendar.js HTTP/1.1" 404 101 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:52 +0100] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 404 116 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
127.0.0.1 - - [06/Dec/2018:00:28:53 +0100] "GET /static/favicon.ico HTTP/1.1" 404 92 "http://127.0.0.1:8000/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
 
So almost all giving 404 and I have done the static files collecting correctly.

Please can you help?

Thank you very much.

**Comment by MaKyOtOx** [comment]
Hi s3c,
Do you run the manager in the development or production mode ? If you run in the production mode (variable `DEBUG` set to `False` in the app/settings.py file), you must deploy a web server/proxy like NGinx.
If you want to start to have a quick look, try to set the DEBUG parameter to True and restart it.

Let me know if it works :)

--Nicolas

**Comment by ghost** [comment]
Hi MakyOtOx,

Thanks for the rapid response! ;)

Well I tried in development mode and then in production mode. 

I have a web server (apache2 on debian based system) (so I have to configure it), but what do you sugest? Better to have Nginx?

Later on I'll try what you suggest and try to see if I can get any information that can help solve the issue.

Then I'll let you know.

Thank you.

Best regards.

**Comment by Mpho777** [comment]
"GET /static/css/bootstrap.css HTTP/1.1" 404 1810 this is my problem

**Comment by Mpho777** [comment]
WARNINGS:
shop.Category: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the ShopConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
shop.Customer: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the ShopConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
shop.Order: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the ShopConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
shop.OrderItem: (models.W042) Auto-created primary key used when not defining a primary key type, by default 
'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the ShopConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
shop.Product: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the ShopConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
shop.ShippingAddress: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the ShopConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 6 issues (0 silenced).

You have 19 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions, shop.
Run 'python manage.py migrate' to apply them.
May 27, 2021 - 14:09:43
Django version 3.2.2, using settings 'starletshop.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[27/May/2021 14:09:48] "GET / HTTP/1.1" 200 7563
[27/May/2021 14:09:48] "GET /static/css/bootstrap.css HTTP/1.1" 404 1810
[27/May/2021 14:09:48] "GET /static/css/main.css HTTP/1.1" 404 1795
[27/May/2021 14:09:48] "GET /static/font-awesome-4.7.0/css/font-awesome.css HTTP/1.1" 404 1876
[27/May/2021 14:09:48] "GET /static/JS/main.js HTTP/1.1" 404 1789
[27/May/2021 14:09:48] "GET /static/JS/bootstrap.js HTTP/1.1" 404 1804
[27/May/2021 14:09:48] "GET /static/images/hero.webp HTTP/1.1" 404 1807
[27/May/2021 14:09:48] "GET /static/images/hero3.jpg HTTP/1.1" 404 1807
[27/May/2021 14:09:48] "GET /static/images/hero4.jpg HTTP/1.1" 404 1807
[27/May/2021 14:09:49] "GET /static/JS/main.js HTTP/1.1" 404 1789
[27/May/2021 14:09:55] "GET /cart/ HTTP/1.1" 200 6628
[27/May/2021 14:09:55] "GET /static/css/main.css HTTP/1.1" 404 1795
[27/May/2021 14:09:55] "GET /static/css/bootstrap.css HTTP/1.1" 404 1810
[27/May/2021 14:09:55] "GET /static/font-awesome-4.7.0/css/font-awesome.css HTTP/1.1" 404 1876
[27/May/2021 14:09:55] "GET /static/JS/main.js HTTP/1.1" 404 1789
[27/May/2021 14:09:56] "GET /static/JS/bootstrap.js HTTP/1.1" 404 1804
[27/May/2021 14:09:56] "GET /static/JS/main.js HTTP/1.1" 404 1789
[27/May/2021 14:10:03] "GET /checkout/ HTTP/1.1" 200 0
[27/May/2021 14:10:11] "GET /static/css/bootstrap.css HTTP/1.1" 404 1810
[27/May/2021 14:10:11] "GET /static/css/main.css HTTP/1.1" 404 1795
[27/May/2021 14:10:11] "GET /static/JS/main.js HTTP/1.1" 404 1789
[27/May/2021 14:10:12] "GET /static/font-awesome-4.7.0/css/font-awesome.css HTTP/1.1" 404 1876
[27/May/2021 14:10:12] "GET /static/JS/main.js HTTP/1.1" 404 1789
[27/May/2021 14:10:16] "GET / HTTP/1.1" 200 7563
[27/May/2021 14:10:16] "GET /static/css/main.css HTTP/1.1" 404 1795
[27/May/2021 14:10:16] "GET /static/css/bootstrap.css HTTP/1.1" 404 1810
[27/May/2021 14:10:16] "GET /static/JS/main.js HTTP/1.1" 404 1789
[27/May/2021 14:10:16] "GET /static/JS/bootstrap.js HTTP/1.1" 404 1804
[27/May/2021 14:10:16] "GET /static/font-awesome-4.7.0/css/font-awesome.css HTTP/1.1" 404 1876
[27/May/2021 14:10:16] "GET /static/images/hero.webp HTTP/1.1" 404 1807
[27/May/2021 14:10:17] "GET /static/images/hero3.jpg HTTP/1.1" 404 1807
[27/May/2021 14:10:17] "GET /static/images/hero4.jpg HTTP/1.1" 404 1807
[27/May/2021 14:10:17] "GET /static/JS/main.js HTTP/1.1" 404 1789

**Comment by unnat404** [comment]
NOTE: This is just another way to access your static files and NOT A FIX for the above problem. 

- **Method** : What you can try is put the static folder inside your app(/s) folders where they are needed, instead of the root(/project) folder, with **_namespacing_** (just a good practice that helps Django differentiate between static files with same names across different apps), and then reference  them accordingly. 
- The reason of the error I think is some error in routing (/urls) in path joining of BASE_DIR and STATIC  files , which we have avoided by in the above method by shifting the static folder's location inside each app

Refer the following Django documentation for better understanding of method:
https://docs.djangoproject.com/en/3.2/intro/tutorial06/
