### ISSUE TITLE
ProgrammingError at /login

### ISSUE THREAD

**Issue by netpanda** [Patrowl/PatrowlDocs#15]
Hi Guys. 
I saw the presentation of the software at bsides, and wanted to try it, however I'm being struggling with it. 
After following the docs, and using docker-compose to get the images up, i'm not able to login with the default creds (admin/Bonjour1!)
I have the 4 images up (nginx, django, rabbit, and postgres) so I dont know whats the issue.  Any ideas? 

![Screenshot_20190325_012341](https://user-images.githubusercontent.com/11094901/54889547-04ddfd80-4e9d-11e9-9b8f-3a815485e948.png)

![Screenshot_20190325_014918](https://user-images.githubusercontent.com/11094901/54890211-3efcce80-4ea0-11e9-81d5-f6aebab4eb2a.png)

**Comment by MaKyOtOx** [comment]
Hi !
It seems you have issues with the db container. Could you please check the db container is up and ready ? Have you tried to restart the web container ?

**Comment by MaKyOtOx** [comment]
up ?
