### ISSUE TITLE
Problème lors de l’installation avec virtualenv

### ISSUE THREAD

**Issue by John33000** [Patrowl/PatrowlDocs#18]
Bonjour,
J'essaye d'installer Patrowl mais j'ai quelque soucis. Je n'utilise pas docker pour l'installation. 
J'en suis ici : cd PatrowlManager
python2.7 -m virtualenv env
source env/bin/activate
pip install -r requirements.txt

J'ai fais un git, je suis aller dans PatrowlManager mais lorsque je lance python2.7 -m virtualenv env j'ai un message d'erreur :  No module name virtualenv et je ne le vois pas dans le dossier PatrowlManager, j'ai vérifié virutalenv est bien installé que dois-je faire s'il vous plait ? Merci

**Comment by MaKyOtOx** [comment]
Bonjour,
Il semblerait que le module python virtualenv ne soit pas bien installé pour python2.7 sur ton OS. Il s'agit d'un module système et il n'est pas présent dans les répertoires PatrowlManager.
Sinon, tu peux essayer un `virtualenv env` directement ?

Hi, it seems the python module 'virtualenv' is not correctly installed for python2.7 on your filesystem. It should be installed with the OS package manager (yum, apt, ...). Try `virtualenv env` (and check the python version ^^)

**Comment by John33000** [comment]
Bonjour,
Si je met : virtualenv env ça me met une erreur python : ```
```
 [root@localhost PatrowlManager]# virtualenv env
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 2, in <module>
    import virtualenv
  File "/root/.local/lib/python2.6/site-packages/virtualenv.py", line 51, in <module>
    print("ERROR: {}".format(sys.exc_info()[1]))
ValueError: zero length field name in format
```

Et si je tape :
 python2.7 -m virtualenv env 

```
[root@localhost ~]# python2.7 -m virtualenv env
/usr/local/bin/python2.7: No module named virtualenv
```

Virtuelenv est vraiment nécessaire ?

**Comment by MaKyOtOx** [comment]
étrange effectivement. Sur quel OS es-tu ? Quelles sont les versions de python installées sur ton serveur/poste (dans ton premier snippet on voit python2.6 et dans le second, on voit python2.7) ?
On peut évidemment faire sans, mais il te faudra modifier plusieurs scripts et fichiers de configuration. Par ailleurs, cela deviendra très compliqué à gérer les dépendances si tu installes plusieurs applications Python sur ton serveur.

**Comment by John33000** [comment]
J'avais un python par défaut mais je ne sais plus lequel, et ensuite j'ai installé le python2.7 car c'était tes prérequis. Je suis sur CentOS 6.10

**Comment by MaKyOtOx** [comment]
Bonjour,
As-tu trouvé une solution pour installer virtualenv sur ton serveur ?
Voici un lien qui pourrait t'aider: https://www.vultr.com/docs/how-to-install-and-use-pip-and-virtualenv-on-centos-6

**Comment by John33000** [comment]
Bonjour,
J'ai suivi votre lien, j'ai mis à jours pip, si je fais un pip install virtualenv il me met une erreur syntax de python il tente d'utiliser python2.6. Et si je tape votre commande python2.7 -m virtualenv env ça me met toujours : No module named virtualenv. Toute les commandes avec "pip" ne fonctionne pas : pip help, la commande du lien : sudo pip install --upgrade pip ça me met des erreurs de module dans des  libs et pourtant il est à jour à la dernière version et bien installé
