### ISSUE TITLE
Trouble installing Patrowl Manager w/ Docker 

### ISSUE THREAD

**Issue by gBuff** [Patrowl/PatrowlDocs#21]
Installation on Debian 9.

After installing Docker & Docker-Compose, and cloning the git, the following command failed : docker-compose build --force-rm

It seems that following line might be missing from the Dockerfile: 
RUN /bin/bash/ -c "python3 -m virtualenv env3" 
(just before : source env3/bin/activate)

It solved my install but I don't know if it was legitimately missing. 

If not, I hope this will help :)

**Comment by MaKyOtOx** [comment]
Hi !
Nice shoot. Just be fixed :)
