### ISSUE TITLE
ERROR - The CSV Template

### ISSUE THREAD

**Issue by meetgyn** [Patrowl/PatrowlDocs#22]
Request Method: | POST
-- | --
http://web:8003/assets/bulkadd
2.2.3
AttributeError
'_csv.reader' object has no attribute 'next'
/opt/patrowl-manager/assets/views.py in bulkadd_asset_view, line 260
/opt/patrowl-manager/env3/bin/python3
3.7.4
['/opt/patrowl-manager',  '/opt/patrowl-manager',  '/opt/patrowl-manager/env3/bin',  '/opt/patrowl-manager/env3/lib/python37.zip',  '/opt/patrowl-manager/env3/lib/python3.7',  '/opt/patrowl-manager/env3/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7',  '/opt/patrowl-manager/env3/lib/python3.7/site-packages']
Wed, 14 Aug 2019 20:03:17 +0200

**Comment by MaKyOtOx** [comment]
Hello ! thk for the issue. This might be due to Python 3 migration :/

**Comment by meetgyn** [comment]
Thank you very much, I will check python

**Comment by MaKyOtOx** [comment]
I keep this issue opened (not fixed yet ;))

**Comment by meetgyn** [comment]
tnks
I believe the mistake is not finding the folder. here neither my server is as follows: / opt / project / PatrowlManager.
the error is returning: /opt/patrowl-manager/assets/views.py in bulkadd_asset_view, line 260

**Comment by meetgyn** [comment]
[errofull.txt](https://github.com/Patrowl/PatrowlDocs/files/3627854/errofull.txt)
