### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by omnia-projetcs** [Patrowl/PatrowlDocs#29]
Hello, some errors:
replace docker-compose -f docker-compose.with-engines.sh up
by
docker-compose -f docker-compose.with-engines.yml up

Add in nginx configurations files (in the case of use of proxy, if not you cannot import file above 5mo)
# disable any limits to avoid HTTP 413 for large image uploads
    client_max_body_size 0;

Thank!

**Comment by MaKyOtOx** [comment]
Done ! Thanks :D
