### ISSUE TITLE
static files didn't load

### ISSUE THREAD

**Issue by alizahedzadeh** [Patrowl/PatrowlDocs#31]
i run server and Css files didn't work correctly

**Comment by MaKyOtOx** [comment]
Hi @alizahedzadeh :
Could you please give us more info ? Could you please ensure you didn't started the server in production mode (DEBUG=False) without a working Nginx ?

**Comment by alizahedzadeh** [comment]
> Hi @alizahedzadeh :
> Could you please give us more info ? Could you please ensure you didn't started the server in production mode (DEBUG=False) without a working Nginx ?

![Screenshot (57)](https://user-images.githubusercontent.com/61024635/96015505-7e10bd00-0e54-11eb-98a9-f8ca8171797a.png)
this is screen shot of my server

**Comment by MaKyOtOx** [comment]
try to start the server with that command: `DEBUG=true python manage.py runserver 0.0.0.0:8000`

**Comment by alizahedzadeh** [comment]
Thanks , my patrowl working correctly now .
