### ISSUE TITLE
Access Refused at /scans/defs/add AMQPLAIN after running a scan

### ISSUE THREAD

**Issue by 0xDagal** [Patrowl/PatrowlDocs#33]
# What did you do?

Running nmap scan

# What did you expect to see?

Seeing the results

# What did you see instead?

An error from amqp/connection.py

# Screens or logs

![image](https://user-images.githubusercontent.com/67750666/116601429-ca23da80-a92a-11eb-8a58-1ae85ed96adc.png)

![image](https://user-images.githubusercontent.com/67750666/116601398-c2fccc80-a92a-11eb-9259-f6cae8d027cf.png)

# Ideas

We use the user Admin as our admin user in settings.py and but in connection.py we see the user as guest which is our Linux user, is there a connection ? Do we need to change one of these ?

**Comment by PRIvATEer35** [comment]
Hi, if you change your user RABBIT_ENV credential in the PatrowlManager/app/settings.py, you have to change it in all the file who are working with RabbitMQ, otherwise it will create an authentificaton conflict as yours.
