### ISSUE TITLE
requirement python-magic-bin==0.4.14

### ISSUE THREAD

**Issue by resource-not-found-blank** [Patrowl/PatrowlDocs#5]
pip install -r requirements.txt
```
...
Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from -r requirements.txt (line 26)) (from versions: )
No matching distribution found for python-magic-bin==0.4.14 (from -r requirements.txt (line 26))
```

Python 2.7.15rc1
pip 18.0 from /home/user/PatrowlManager/env/local/lib/python2.7/site-packages/pip (python 2.7)
Ubuntu 18.04 LTS (Linux patrowl 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by thalesmv** [comment]
I removed the line `python-magic-bin==0.4.14`  from [requirements](https://github.com/Patrowl/PatrowlManager/blob/master/requirements.txt) as it's not intended for linux. I don't believe removing it has caused in issues so far.

**Comment by resource-not-found-blank** [comment]
Thanks @thalesmv 
I also chose this path. Maybe this package need remove from requirements. I wait for a response from the developers

**Comment by MaKyOtOx** [comment]
Hi all, sorry for the delay. `python-magic-bin` is not required. It has to be removed !
Thx all :)
