### ISSUE TITLE
Version in "./docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by iamburakcinar** [Patrowl/PatrowlDocs#7]
Im getting error when i run `docker-compose build --force-rm` command.

root@patrowl:~/bb# git clone https://github.com/Patrowl/PatrowlManager.git
Cloning into 'PatrowlManager'...
remote: Enumerating objects: 294, done.
remote: Counting objects: 100% (294/294), done.
remote: Compressing objects: 100% (177/177), done.
remote: Total 692 (delta 169), reused 203 (delta 116), pack-reused 398
Receiving objects: 100% (692/692), 1.20 MiB | 1.96 MiB/s, done.
Resolving deltas: 100% (349/349), done.
root@patrowl:~/bb# cd PatrowlManager
root@patrowl:~/bb/PatrowlManager# 
root@patrowl:~/bb/PatrowlManager# docker-compose build --force-rm
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
root@patrowl:~/bb/PatrowlManager#

**Comment by MaKyOtOx** [comment]
Hi,
Which version of docker-compose have you installed ? The PatrowlManager docker-compose-file require at least the version 3.7. Otherwise, try to remove the version in the .yml
For my part, I'll test if it works with previous versions of docker-compose.

**Comment by iamburakcinar** [comment]
hi,
its worked after i've upgraded to latest version of ubuntu and docker engine. 
thanks.
