### ISSUE TITLE
Add New Scan - Can't find assets

### ISSUE THREAD

**Issue by Athrekas** [Patrowl/PatrowlDocs#9]
![image](https://user-images.githubusercontent.com/23584901/47363469-2c0a8600-d6d7-11e8-8b67-8be08592a21b.png)

![image](https://user-images.githubusercontent.com/23584901/47363587-6ecc5e00-d6d7-11e8-92f6-bdb01383f377.png)

**Comment by Athrekas** [comment]
If finds the Asset via IP, not name.

**Comment by MaKyOtOx** [comment]
yes exactly. But it could be a good idea to search on the asset name too
